// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msu.proto

package msu

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsuIn struct {
	Timestamp              uint64   `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	AndromedaPID           uint32   `protobuf:"varint,2,opt,name=AndromedaPID,proto3" json:"AndromedaPID,omitempty"`
	AndromedaLID           uint32   `protobuf:"varint,3,opt,name=AndromedaLID,proto3" json:"AndromedaLID,omitempty"`
	AndromedaPoint         uint32   `protobuf:"varint,4,opt,name=AndromedaPoint,proto3" json:"AndromedaPoint,omitempty"`
	Mtp3DPC                uint32   `protobuf:"varint,5,opt,name=Mtp3DPC,proto3" json:"Mtp3DPC,omitempty"`
	Mtp3OPC                uint32   `protobuf:"varint,6,opt,name=Mtp3OPC,proto3" json:"Mtp3OPC,omitempty"`
	Mtp3NI                 uint32   `protobuf:"varint,7,opt,name=Mtp3NI,proto3" json:"Mtp3NI,omitempty"`
	SccpCallingAddress     string   `protobuf:"bytes,8,opt,name=SccpCallingAddress,proto3" json:"SccpCallingAddress,omitempty"`
	SccpCalledAddress      string   `protobuf:"bytes,9,opt,name=SccpCalledAddress,proto3" json:"SccpCalledAddress,omitempty"`
	TcapMessageType        string   `protobuf:"bytes,10,opt,name=TcapMessageType,proto3" json:"TcapMessageType,omitempty"`
	TcapOTID               uint32   `protobuf:"varint,11,opt,name=TcapOTID,proto3" json:"TcapOTID,omitempty"`
	TcapDTID               uint32   `protobuf:"varint,12,opt,name=TcapDTID,proto3" json:"TcapDTID,omitempty"`
	MapOperationalCode     uint32   `protobuf:"varint,13,opt,name=MapOperationalCode,proto3" json:"MapOperationalCode,omitempty"`
	MapOperationalCodeName string   `protobuf:"bytes,14,opt,name=MapOperationalCodeName,proto3" json:"MapOperationalCodeName,omitempty"`
	CapOperationalCode     uint32   `protobuf:"varint,16,opt,name=CapOperationalCode,proto3" json:"CapOperationalCode,omitempty"`
	CapOperationalCodeName string   `protobuf:"bytes,17,opt,name=CapOperationalCodeName,proto3" json:"CapOperationalCodeName,omitempty"`
	MessageData            string   `protobuf:"bytes,18,opt,name=MessageData,proto3" json:"MessageData,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *MsuIn) Reset()         { *m = MsuIn{} }
func (m *MsuIn) String() string { return proto.CompactTextString(m) }
func (*MsuIn) ProtoMessage()    {}
func (*MsuIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e886f7daac93edad, []int{0}
}

func (m *MsuIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsuIn.Unmarshal(m, b)
}
func (m *MsuIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsuIn.Marshal(b, m, deterministic)
}
func (m *MsuIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsuIn.Merge(m, src)
}
func (m *MsuIn) XXX_Size() int {
	return xxx_messageInfo_MsuIn.Size(m)
}
func (m *MsuIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsuIn.DiscardUnknown(m)
}

var xxx_messageInfo_MsuIn proto.InternalMessageInfo

func (m *MsuIn) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsuIn) GetAndromedaPID() uint32 {
	if m != nil {
		return m.AndromedaPID
	}
	return 0
}

func (m *MsuIn) GetAndromedaLID() uint32 {
	if m != nil {
		return m.AndromedaLID
	}
	return 0
}

func (m *MsuIn) GetAndromedaPoint() uint32 {
	if m != nil {
		return m.AndromedaPoint
	}
	return 0
}

func (m *MsuIn) GetMtp3DPC() uint32 {
	if m != nil {
		return m.Mtp3DPC
	}
	return 0
}

func (m *MsuIn) GetMtp3OPC() uint32 {
	if m != nil {
		return m.Mtp3OPC
	}
	return 0
}

func (m *MsuIn) GetMtp3NI() uint32 {
	if m != nil {
		return m.Mtp3NI
	}
	return 0
}

func (m *MsuIn) GetSccpCallingAddress() string {
	if m != nil {
		return m.SccpCallingAddress
	}
	return ""
}

func (m *MsuIn) GetSccpCalledAddress() string {
	if m != nil {
		return m.SccpCalledAddress
	}
	return ""
}

func (m *MsuIn) GetTcapMessageType() string {
	if m != nil {
		return m.TcapMessageType
	}
	return ""
}

func (m *MsuIn) GetTcapOTID() uint32 {
	if m != nil {
		return m.TcapOTID
	}
	return 0
}

func (m *MsuIn) GetTcapDTID() uint32 {
	if m != nil {
		return m.TcapDTID
	}
	return 0
}

func (m *MsuIn) GetMapOperationalCode() uint32 {
	if m != nil {
		return m.MapOperationalCode
	}
	return 0
}

func (m *MsuIn) GetMapOperationalCodeName() string {
	if m != nil {
		return m.MapOperationalCodeName
	}
	return ""
}

func (m *MsuIn) GetCapOperationalCode() uint32 {
	if m != nil {
		return m.CapOperationalCode
	}
	return 0
}

func (m *MsuIn) GetCapOperationalCodeName() string {
	if m != nil {
		return m.CapOperationalCodeName
	}
	return ""
}

func (m *MsuIn) GetMessageData() string {
	if m != nil {
		return m.MessageData
	}
	return ""
}

type MsuAnswer struct {
	Answer               uint32   `protobuf:"varint,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsuAnswer) Reset()         { *m = MsuAnswer{} }
func (m *MsuAnswer) String() string { return proto.CompactTextString(m) }
func (*MsuAnswer) ProtoMessage()    {}
func (*MsuAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e886f7daac93edad, []int{1}
}

func (m *MsuAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsuAnswer.Unmarshal(m, b)
}
func (m *MsuAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsuAnswer.Marshal(b, m, deterministic)
}
func (m *MsuAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsuAnswer.Merge(m, src)
}
func (m *MsuAnswer) XXX_Size() int {
	return xxx_messageInfo_MsuAnswer.Size(m)
}
func (m *MsuAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsuAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_MsuAnswer proto.InternalMessageInfo

func (m *MsuAnswer) GetAnswer() uint32 {
	if m != nil {
		return m.Answer
	}
	return 0
}

func init() {
	proto.RegisterType((*MsuIn)(nil), "msu.MsuIn")
	proto.RegisterType((*MsuAnswer)(nil), "msu.MsuAnswer")
}

func init() { proto.RegisterFile("msu.proto", fileDescriptor_e886f7daac93edad) }

var fileDescriptor_e886f7daac93edad = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0xab, 0x9b, 0x40,
	0x14, 0xc5, 0x6b, 0xf3, 0xd7, 0x9b, 0x3f, 0x6d, 0xee, 0x22, 0x0c, 0xa1, 0x0b, 0xb1, 0x50, 0x5c,
	0x94, 0x2c, 0x1a, 0xc8, 0x3e, 0x8c, 0x1b, 0x21, 0x46, 0xb1, 0x7e, 0x81, 0x69, 0x1c, 0x82, 0x10,
	0x75, 0x70, 0x94, 0xf2, 0x3e, 0xc7, 0xfb, 0xc2, 0x8f, 0x19, 0xe3, 0xf3, 0x25, 0xf1, 0xed, 0xee,
	0x39, 0xbf, 0x33, 0x9c, 0x8b, 0x5e, 0x30, 0x33, 0x59, 0x6f, 0x45, 0x59, 0x54, 0x05, 0x0e, 0x32,
	0x59, 0xdb, 0xaf, 0x23, 0x18, 0xf9, 0xb2, 0xf6, 0x72, 0xfc, 0x01, 0x66, 0x9c, 0x66, 0x5c, 0x56,
	0x2c, 0x13, 0xc4, 0xb0, 0x0c, 0x67, 0x18, 0x75, 0x06, 0xda, 0x30, 0x3f, 0xe4, 0x49, 0x59, 0x64,
	0x3c, 0x61, 0xa1, 0xe7, 0x92, 0xaf, 0x96, 0xe1, 0x2c, 0xa2, 0x3b, 0xef, 0x2e, 0x73, 0xf4, 0x5c,
	0x32, 0x78, 0xc8, 0x1c, 0x3d, 0x17, 0x7f, 0xc1, 0xb2, 0x7b, 0x53, 0xa4, 0x79, 0x45, 0x86, 0x3a,
	0xf5, 0xe0, 0x22, 0x81, 0x89, 0x5f, 0x89, 0x9d, 0x1b, 0x52, 0x32, 0xd2, 0x81, 0x56, 0xb6, 0x24,
	0x08, 0x29, 0x19, 0x77, 0x24, 0x08, 0x29, 0xae, 0x61, 0xac, 0xc6, 0x93, 0x47, 0x26, 0x1a, 0xdc,
	0x14, 0x6e, 0x01, 0xff, 0x9e, 0xcf, 0x82, 0xb2, 0xeb, 0x35, 0xcd, 0x2f, 0x87, 0x24, 0x29, 0xb9,
	0x94, 0x64, 0x6a, 0x19, 0x8e, 0x19, 0xf5, 0x10, 0xfc, 0x0d, 0xab, 0xd6, 0xe5, 0x49, 0x1b, 0x37,
	0x75, 0xfc, 0x19, 0xa0, 0x03, 0xdf, 0xe2, 0x33, 0x13, 0x3e, 0x97, 0x92, 0x5d, 0x78, 0xfc, 0x22,
	0x38, 0x01, 0x9d, 0x7d, 0xb4, 0x71, 0x03, 0x53, 0x65, 0x05, 0xb1, 0xe7, 0x92, 0x99, 0xde, 0xf0,
	0x5d, 0xb7, 0xcc, 0x55, 0x6c, 0xde, 0x31, 0xa5, 0xd5, 0xfe, 0x3e, 0x13, 0x81, 0xe0, 0x25, 0xab,
	0xd2, 0x22, 0x67, 0x57, 0x5a, 0x24, 0x9c, 0x2c, 0x74, 0xaa, 0x87, 0xe0, 0x1e, 0xd6, 0xcf, 0xee,
	0x89, 0x65, 0x9c, 0x2c, 0xf5, 0x62, 0x9f, 0x50, 0xd5, 0x43, 0x9f, 0x7b, 0xbe, 0x37, 0x3d, 0xb4,
	0xb7, 0x87, 0xf6, 0xf7, 0xac, 0x9a, 0x9e, 0x7e, 0x8a, 0x16, 0xcc, 0x6e, 0x9f, 0xc5, 0x65, 0x15,
	0x23, 0xa8, 0xc3, 0x1f, 0x2d, 0xfb, 0x27, 0x98, 0xbe, 0xac, 0x0f, 0xb9, 0xfc, 0xcf, 0x4b, 0xf5,
	0x5b, 0x9b, 0x49, 0x5f, 0xe5, 0x22, 0xba, 0xa9, 0x3f, 0x7b, 0x00, 0x15, 0x3e, 0x16, 0x2c, 0xe1,
	0x25, 0x3a, 0x30, 0x55, 0x93, 0x72, 0x10, 0xb6, 0xea, 0xca, 0xf5, 0x59, 0x6f, 0x96, 0xed, 0xdc,
	0xbc, 0xb2, 0xbf, 0xfc, 0x1b, 0xeb, 0xf3, 0xdf, 0xbd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x65, 0xce,
	0xf4, 0x05, 0x0b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataLoaderClient is the client API for DataLoader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataLoaderClient interface {
	LoadData(ctx context.Context, in *MsuIn, opts ...grpc.CallOption) (*MsuAnswer, error)
}

type dataLoaderClient struct {
	cc grpc.ClientConnInterface
}

func NewDataLoaderClient(cc grpc.ClientConnInterface) DataLoaderClient {
	return &dataLoaderClient{cc}
}

func (c *dataLoaderClient) LoadData(ctx context.Context, in *MsuIn, opts ...grpc.CallOption) (*MsuAnswer, error) {
	out := new(MsuAnswer)
	err := c.cc.Invoke(ctx, "/msu.DataLoader/LoadData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataLoaderServer is the server API for DataLoader service.
type DataLoaderServer interface {
	LoadData(context.Context, *MsuIn) (*MsuAnswer, error)
}

// UnimplementedDataLoaderServer can be embedded to have forward compatible implementations.
type UnimplementedDataLoaderServer struct {
}

func (*UnimplementedDataLoaderServer) LoadData(ctx context.Context, req *MsuIn) (*MsuAnswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadData not implemented")
}

func RegisterDataLoaderServer(s *grpc.Server, srv DataLoaderServer) {
	s.RegisterService(&_DataLoader_serviceDesc, srv)
}

func _DataLoader_LoadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsuIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataLoaderServer).LoadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msu.DataLoader/LoadData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataLoaderServer).LoadData(ctx, req.(*MsuIn))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataLoader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msu.DataLoader",
	HandlerType: (*DataLoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadData",
			Handler:    _DataLoader_LoadData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msu.proto",
}
